
import { BasePokemon, GymLeaderInfo } from './types';

export const INITIAL_POKEMON_LIST: BasePokemon[] = [
  { "name": "chespin", "id": 650, "routes": [] },
  { "name": "quilladin", "id": 651, "routes": [] },
  { "name": "chesnaught", "id": 652, "routes": [] },
  { "name": "fennekin", "id": 653, "routes": [] },
  { "name": "braixen", "id": 654, "routes": [] },
  { "name": "delphox", "id": 655, "routes": [] },
  { "name": "froakie", "id": 656, "routes": [] },
  { "name": "frogadier", "id": 657, "routes": [] },
  { "name": "greninja", "id": 658, "routes": [] },
  { "name": "bunnelby", "id": 659, "routes": ["Route 2", "Route 3", "Route 22"] },
  { "name": "diggersby", "id": 660, "routes": ["Route 22"] },
  { "name": "zigzagoon", "id": 263, "routes": [] },
  { "name": "linoone", "id": 264, "routes": [] },
  { "name": "fletchling", "id": 661, "routes": ["Route 2"] },
  { "name": "fletchinder", "id": 662, "routes": [] },
  { "name": "talonflame", "id": 663, "routes": [] },
  { "name": "pidgey", "id": 16, "routes": ["Route 2", "Route 3", "Route 22"] },
  { "name": "pidgeotto", "id": 17, "routes": [] },
  { "name": "pidgeot", "id": 18, "routes": [] },
  { "name": "scatterbug", "id": 664, "routes": ["Route 2"] },
  { "name": "spewpa", "id": 665, "routes": [] },
  { "name": "vivillon", "id": 666, "routes": [] },
  { "name": "caterpie", "id": 10, "routes": ["Route 2"] },
  { "name": "metapod", "id": 11, "routes": ["Route 22"] },
  { "name": "butterfree", "id": 12, "routes": ["Route 22"] },
  { "name": "weedle", "id": 13, "routes": ["Route 2"] },
  { "name": "kakuna", "id": 14, "routes": ["Route 22"] },
  { "name": "beedrill", "id": 15, "routes": ["Route 22"] },
  { "name": "pansage", "id": 511, "routes": [] },
  { "name": "simisage", "id": 512, "routes": [] },
  { "name": "pansear", "id": 513, "routes": [] },
  { "name": "simisear", "id": 514, "routes": [] },
  { "name": "panpour", "id": 515, "routes": [] },
  { "name": "simipour", "id": 516, "routes": [] },
  { "name": "pichu", "id": 172, "routes": [] },
  { "name": "pikachu", "id": 25, "routes": ["Route 3"] },
  { "name": "raichu", "id": 26, "routes": [] },
  { "name": "bidoof", "id": 399, "routes": ["Route 3"] },
  { "name": "bibarel", "id": 400, "routes": ["Route 22"] },
  { "name": "dunsparce", "id": 206, "routes": ["Route 3", "Route 22"] },
  { "name": "azurill", "id": 298, "routes": ["Route 3", "Route 22"] },
  { "name": "marill", "id": 183, "routes": ["Route 3", "Route 22"] },
  { "name": "azumarill", "id": 184, "routes": ["Route 22"] },
  { "name": "burmy", "id": 412, "routes": ["Route 3"] },
  { "name": "wormadam", "id": 413, "routes": [] },
  { "name": "mothim", "id": 414, "routes": [] },
  { "name": "surskit", "id": 283, "routes": [] },
  { "name": "masquerain", "id": 284, "routes": ["Route 3", "Route 22"] },
  { "name": "magikarp", "id": 129, "routes": [] },
  { "name": "gyarados", "id": 130, "routes": [] },
  { "name": "corphish", "id": 341, "routes": ["Route 3"] },
  { "name": "crawdaunt", "id": 342, "routes": ["Route 3"] },
  { "name": "goldeen", "id": 118, "routes": ["Route 3", "Route 22"] },
  { "name": "seaking", "id": 119, "routes": [] },
  { "name": "carvanha", "id": 318, "routes": ["Route 22"] },
  { "name": "sharpedo", "id": 319, "routes": ["Route 22"] },
  { "name": "litleo", "id": 667, "routes": [] },
  { "name": "pyroar", "id": 668, "routes": [] },
  { "name": "psyduck", "id": 54, "routes": [] },
  { "name": "golduck", "id": 55, "routes": [] },
  { "name": "farfetchd", "id": 83, "routes": ["Route 22"] },
  { "name": "riolu", "id": 447, "routes": ["Route 22"] },
  { "name": "lucario", "id": 448, "routes": [] },
  { "name": "ralts", "id": 280, "routes": ["Route 4"] },
  { "name": "kirlia", "id": 281, "routes": [] },
  { "name": "gardevoir", "id": 282, "routes": [] },
  { "name": "gallade", "id": 475, "routes": [] },
  { "name": "flabebe", "id": 669, "routes": ["Route 4", "Route 7"] },
  { "name": "floette", "id": 670, "routes": [] },
  { "name": "florges", "id": 671, "routes": [] },
  { "name": "budew", "id": 406, "routes": ["Route 4"] },
  { "name": "roselia", "id": 315, "routes": ["Route 7"] },
  { "name": "roserade", "id": 407, "routes": [] },
  { "name": "ledyba", "id": 165, "routes": ["Route 4"] },
  { "name": "ledian", "id": 166, "routes": [] },
  { "name": "combee", "id": 415, "routes": ["Route 4"] },
  { "name": "vespiquen", "id": 416, "routes": [] },
  { "name": "skitty", "id": 300, "routes": ["Route 4"] },
  { "name": "delcatty", "id": 301, "routes": [] },
  { "name": "bulbasaur", "id": 1, "routes": [] },
  { "name": "ivysaur", "id": 2, "routes": [] },
  { "name": "venusaur", "id": 3, "routes": [] },
  { "name": "charmander", "id": 4, "routes": [] },
  { "name": "charmeleon", "id": 5, "routes": [] },
  { "name": "charizard", "id": 6, "routes": [] },
  { "name": "squirtle", "id": 7, "routes": [] },
  { "name": "wartortle", "id": 8, "routes": [] },
  { "name": "blastoise", "id": 9, "routes": [] },
  { "name": "skiddo", "id": 672, "routes": ["Route 5"] },
  { "name": "gogoat", "id": 673, "routes": [] },
  { "name": "pancham", "id": 674, "routes": ["Route 5"] },
  { "name": "pangoro", "id": 675, "routes": [] },
  { "name": "furfrou", "id": 676, "routes": [] },
  { "name": "doduo", "id": 84, "routes": ["Route 5"] },
  { "name": "dodrio", "id": 85, "routes": [] },
  { "name": "plusle", "id": 311, "routes": ["Route 5"] },
  { "name": "minun", "id": 312, "routes": ["Route 5"] },
  { "name": "gulpin", "id": 316, "routes": ["Route 5"] },
  { "name": "swalot", "id": 317, "routes": [] },
  { "name": "scraggy", "id": 559, "routes": [] },
  { "name": "scrafty", "id": 560, "routes": [] },
  { "name": "abra", "id": 63, "routes": ["Route 5"] },
  { "name": "kadabra", "id": 64, "routes": [] },
  { "name": "alakazam", "id": 65, "routes": [] },
  { "name": "oddish", "id": 43, "routes": ["Route 6"] },
  { "name": "gloom", "id": 44, "routes": [] },
  { "name": "vileplume", "id": 45, "routes": [] },
  { "name": "bellossom", "id": 182, "routes": [] },
  { "name": "sentret", "id": 161, "routes": ["Route 6"] },
  { "name": "furret", "id": 162, "routes": [] },
  { "name": "nincada", "id": 290, "routes": ["Route 6"] },
  { "name": "ninjask", "id": 291, "routes": [] },
  { "name": "shedinja", "id": 292, "routes": [] },
  { "name": "espurr", "id": 677, "routes": ["Route 6"] },
  { "name": "meowstic", "id": 678, "routes": [] },
  { "name": "kecleon", "id": 352, "routes": ["Route 6"] },
  { "name": "honedge", "id": 679, "routes": ["Route 6"] },
  { "name": "doublade", "id": 680, "routes": [] },
  { "name": "aegislash", "id": 681, "routes": [] },
  { "name": "venipede", "id": 543, "routes": [] },
  { "name": "whirlipede", "id": 544, "routes": [] },
  { "name": "scolipede", "id": 545, "routes": [] },
  { "name": "audino", "id": 531, "routes": [] },
  { "name": "smeargle", "id": 235, "routes": ["Route 7"] },
  { "name": "croagunk", "id": 453, "routes": ["Route 7"] },
  { "name": "toxicroak", "id": 454, "routes": [] },
  { "name": "ducklett", "id": 580, "routes": ["Route 7"] },
  { "name": "swanna", "id": 581, "routes": [] },
  { "name": "spritzee", "id": 682, "routes": [] },
  { "name": "aromatisse", "id": 683, "routes": [] },
  { "name": "swirlix", "id": 684, "routes": [] },
  { "name": "slurpuff", "id": 685, "routes": [] },
  { "name": "volbeat", "id": 313, "routes": ["Route 7"] },
  { "name": "illumise", "id": 314, "routes": ["Route 7"] },
  { "name": "hoppip", "id": 187, "routes": ["Route 7"] },
  { "name": "skiploom", "id": 188, "routes": [] },
  { "name": "jumpluff", "id": 189, "routes": [] },
  { "name": "munchlax", "id": 446, "routes": [] },
  { "name": "snorlax", "id": 143, "routes": [] },
  { "name": "whismur", "id": 293, "routes": [] },
  { "name": "loudred", "id": 294, "routes": [] },
  { "name": "exploud", "id": 295, "routes": [] },
  { "name": "meditite", "id": 307, "routes": [] },
  { "name": "medicham", "id": 308, "routes": [] },
  { "name": "zubat", "id": 41, "routes": [] },
  { "name": "golbat", "id": 42, "routes": [] },
  { "name": "crobat", "id": 169, "routes": [] },
  { "name": "axew", "id": 610, "routes": [] },
  { "name": "fraxure", "id": 611, "routes": [] },
  { "name": "haxorus", "id": 612, "routes": [] },
  { "name": "diancie", "id": 719, "routes": [] },
  { "name": "hoopa", "id": 720, "routes": [] },
  { "name": "volcanion", "id": 721, "routes": [] },
  { "name": "drifloon", "id": 425, "routes": ["Route 8"] },
  { "name": "drifblim", "id": 426, "routes": [] },
  { "name": "mienfoo", "id": 619, "routes": ["Route 8"] },
  { "name": "mienshao", "id": 620, "routes": [] },
  { "name": "zangoose", "id": 335, "routes": ["Route 8"] },
  { "name": "seviper", "id": 336, "routes": ["Route 8"] },
  { "name": "spoink", "id": 325, "routes": ["Route 8"] },
  { "name": "grumpig", "id": 326, "routes": [] },
  { "name": "absol", "id": 359, "routes": ["Route 8"] },
  { "name": "inkay", "id": 686, "routes": ["Route 8"] },
  { "name": "malamar", "id": 687, "routes": [] },
  { "name": "lunatone", "id": 337, "routes": [] },
  { "name": "solrock", "id": 338, "routes": [] },
  { "name": "bagon", "id": 371, "routes": [] },
  { "name": "shelgon", "id": 372, "routes": [] },
  { "name": "salamence", "id": 373, "routes": [] },
  { "name": "wingull", "id": 278, "routes": [] },
  { "name": "pelipper", "id": 279, "routes": [] },
  { "name": "taillow", "id": 276, "routes": [] },
  { "name": "swellow", "id": 277, "routes": [] },
  { "name": "binacle", "id": 688, "routes": [] },
  { "name": "barbaracle", "id": 689, "routes": [] },
  { "name": "dwebble", "id": 557, "routes": [] },
  { "name": "crustle", "id": 558, "routes": [] },
  { "name": "tentacool", "id": 72, "routes": [] },
  { "name": "tentacruel", "id": 73, "routes": [] },
  { "name": "wailmer", "id": 320, "routes": [] },
  { "name": "wailord", "id": 321, "routes": [] },
  { "name": "luvdisc", "id": 370, "routes": [] },
  { "name": "skrelp", "id": 690, "routes": [] },
  { "name": "dragalge", "id": 691, "routes": [] },
  { "name": "clauncher", "id": 692, "routes": [] },
  { "name": "clawitzer", "id": 693, "routes": [] },
  { "name": "staryu", "id": 120, "routes": [] },
  { "name": "starmie", "id": 121, "routes": [] },
  { "name": "shellder", "id": 90, "routes": [] },
  { "name": "cloyster", "id": 91, "routes": [] },
  { "name": "qwilfish", "id": 211, "routes": [] },
  { "name": "horsea", "id": 116, "routes": [] },
  { "name": "seadra", "id": 117, "routes": [] },
  { "name": "kingdra", "id": 230, "routes": [] },
  { "name": "relicanth", "id": 369, "routes": [] },
  { "name": "sandile", "id": 551, "routes": ["Route 9"] },
  { "name": "krokorok", "id": 552, "routes": [] },
  { "name": "krookodile", "id": 553, "routes": [] },
  { "name": "helioptile", "id": 694, "routes": ["Route 9"] },
  { "name": "heliolisk", "id": 695, "routes": [] },
  { "name": "hippopotas", "id": 449, "routes": ["Route 9"] },
  { "name": "hippowdon", "id": 450, "routes": [] },
  { "name": "rhyhorn", "id": 111, "routes": [] },
  { "name": "rhydon", "id": 112, "routes": [] },
  { "name": "rhyperior", "id": 464, "routes": [] },
  { "name": "onix", "id": 95, "routes": [] },
  { "name": "steelix", "id": 208, "routes": [] },
  { "name": "woobat", "id": 527, "routes": [] },
  { "name": "swoobat", "id": 528, "routes": [] },
  { "name": "machop", "id": 66, "routes": [] },
  { "name": "machoke", "id": 67, "routes": [] },
  { "name": "machamp", "id": 68, "routes": [] },
  { "name": "cubone", "id": 104, "routes": [] },
  { "name": "marowak", "id": 105, "routes": [] },
  { "name": "kangaskhan", "id": 115, "routes": [] },
  { "name": "mawile", "id": 303, "routes": [] },
  { "name": "tyrunt", "id": 696, "routes": [] },
  { "name": "tyrantrum", "id": 697, "routes": [] },
  { "name": "amaura", "id": 698, "routes": [] },
  { "name": "aurorus", "id": 699, "routes": [] },
  { "name": "aerodactyl", "id": 142, "routes": [] },
  { "name": "ferroseed", "id": 597, "routes": [] },
  { "name": "ferrothorn", "id": 598, "routes": [] },
  { "name": "snubbull", "id": 209, "routes": [] },
  { "name": "granbull", "id": 210, "routes": [] },
  { "name": "electrike", "id": 309, "routes": ["Route 10"] },
  { "name": "manectric", "id": 310, "routes": [] },
  { "name": "houndour", "id": 228, "routes": ["Route 10"] },
  { "name": "houndoom", "id": 229, "routes": [] },
  { "name": "eevee", "id": 133, "routes": ["Route 10"] },
  { "name": "vaporeon", "id": 134, "routes": [] },
  { "name": "jolteon", "id": 135, "routes": [] },
  { "name": "flareon", "id": 136, "routes": [] },
  { "name": "espeon", "id": 196, "routes": [] },
  { "name": "umbreon", "id": 197, "routes": [] },
  { "name": "leafeon", "id": 470, "routes": [] },
  { "name": "glaceon", "id": 471, "routes": [] },
  { "name": "sylveon", "id": 700, "routes": [] },
  { "name": "emolga", "id": 587, "routes": ["Route 10"] },
  { "name": "yanma", "id": 193, "routes": [] },
  { "name": "yanmega", "id": 469, "routes": [] },
  { "name": "hawlucha", "id": 701, "routes": ["Route 10"] },
  { "name": "sigilyph", "id": 561, "routes": ["Route 10"] },
  { "name": "golett", "id": 622, "routes": ["Route 10"] },
  { "name": "golurk", "id": 623, "routes": [] },
  { "name": "nosepass", "id": 299, "routes": [] },
  { "name": "probopass", "id": 476, "routes": [] },
  { "name": "makuhita", "id": 296, "routes": [] },
  { "name": "hariyama", "id": 297, "routes": ["Route 11"] },
  { "name": "throh", "id": 538, "routes": ["Route 11"] },
  { "name": "sawk", "id": 539, "routes": ["Route 11"] },
  { "name": "starly", "id": 396, "routes": [] },
  { "name": "staravia", "id": 397, "routes": ["Route 11"] },
  { "name": "staraptor", "id": 398, "routes": [] },
  { "name": "stunky", "id": 434, "routes": ["Route 11"] },
  { "name": "skuntank", "id": 435, "routes": [] },
  { "name": "nidoran-f", "id": 29, "routes": ["Route 11"] },
  { "name": "nidorina", "id": 30, "routes": [] },
  { "name": "nidoqueen", "id": 31, "routes": [] },
  { "name": "nidoran-m", "id": 32, "routes": ["Route 11"] },
  { "name": "nidorino", "id": 33, "routes": [] },
  { "name": "nidoking", "id": 34, "routes": [] },
  { "name": "dedenne", "id": 702, "routes": ["Route 11"] },
  { "name": "chingling", "id": 433, "routes": ["Route 11"] },
  { "name": "chimecho", "id": 358, "routes": [] },
  { "name": "mime-jr", "id": 439, "routes": [] },
  { "name": "mr-mime", "id": 122, "routes": [] },
  { "name": "solosis", "id": 577, "routes": [] },
  { "name": "duosion", "id": 578, "routes": [] },
  { "name": "reuniclus", "id": 579, "routes": [] },
  { "name": "wynaut", "id": 360, "routes": [] },
  { "name": "wobbuffet", "id": 202, "routes": [] },
  { "name": "roggenrola", "id": 524, "routes": [] },
  { "name": "boldore", "id": 525, "routes": [] },
  { "name": "gigalith", "id": 526, "routes": [] },
  { "name": "sableye", "id": 302, "routes": [] },
  { "name": "carbink", "id": 703, "routes": [] },
  { "name": "tauros", "id": 128, "routes": ["Route 12"] },
  { "name": "miltank", "id": 241, "routes": ["Route 12"] },
  { "name": "mareep", "id": 179, "routes": [] },
  { "name": "flaaffy", "id": 180, "routes": [] },
  { "name": "ampharos", "id": 181, "routes": [] },
  { "name": "pinsir", "id": 127, "routes": ["Route 12"] },
  { "name": "heracross", "id": 214, "routes": ["Route 12"] },
  { "name": "pachirisu", "id": 417, "routes": ["Route 12"] },
  { "name": "slowpoke", "id": 79, "routes": ["Route 12"] },
  { "name": "slowbro", "id": 80, "routes": [] },
  { "name": "slowking", "id": 199, "routes": [] },
  { "name": "exeggcute", "id": 102, "routes": ["Route 12"] },
  { "name": "exeggutor", "id": 103, "routes": [] },
  { "name": "chatot", "id": 441, "routes": ["Route 12"] },
  { "name": "mantyke", "id": 458, "routes": ["Route 12"] },
  { "name": "mantine", "id": 226, "routes": [] },
  { "name": "clamperl", "id": 366, "routes": ["Route 12"] },
  { "name": "huntail", "id": 367, "routes": ["Route 12"] },
  { "name": "gorebyss", "id": 368, "routes": ["Route 12"] },
  { "name": "remoraid", "id": 223, "routes": ["Route 12"] },
  { "name": "octillery", "id": 224, "routes": ["Route 12"] },
  { "name": "corsola", "id": 222, "routes": [] },
  { "name": "chinchou", "id": 170, "routes": [] },
  { "name": "lanturn", "id": 171, "routes": [] },
  { "name": "alomomola", "id": 594, "routes": [] },
  { "name": "lapras", "id": 131, "routes": [] },
  { "name": "articuno", "id": 144, "routes": [] },
  { "name": "zapdos", "id": 145, "routes": [] },
  { "name": "moltres", "id": 146, "routes": [] },
  { "name": "diglett", "id": 50, "routes": [] },
  { "name": "dugtrio", "id": 51, "routes": ["Route 13"] },
  { "name": "trapinch", "id": 328, "routes": ["Route 13"] },
  { "name": "vibrava", "id": 329, "routes": [] },
  { "name": "flygon", "id": 330, "routes": [] },
  { "name": "gible", "id": 443, "routes": ["Route 13"] },
  { "name": "gabite", "id": 444, "routes": [] },
  { "name": "garchomp", "id": 445, "routes": [] },
  { "name": "geodude", "id": 74, "routes": ["Route 18"] },
  { "name": "graveler", "id": 75, "routes": ["Route 18"] },
  { "name": "golem", "id": 76, "routes": [] },
  { "name": "slugma", "id": 218, "routes": [] },
  { "name": "magcargo", "id": 219, "routes": [] },
  { "name": "shuckle", "id": 213, "routes": [] },
  { "name": "skorupi", "id": 451, "routes": ["Route 14", "Route 15"] },
  { "name": "drapion", "id": 452, "routes": [] },
  { "name": "wooper", "id": 194, "routes": [] },
  { "name": "quagsire", "id": 195, "routes": ["Route 14", "Route 19"] },
  { "name": "goomy", "id": 704, "routes": ["Route 14"] },
  { "name": "sliggoo", "id": 705, "routes": ["Route 19"] },
  { "name": "goodra", "id": 706, "routes": [] },
  { "name": "karrablast", "id": 588, "routes": ["Route 14", "Route 19"] },
  { "name": "escavalier", "id": 589, "routes": [] },
  { "name": "shelmet", "id": 616, "routes": ["Route 14", "Route 19"] },
  { "name": "accelgor", "id": 617, "routes": [] },
  { "name": "bellsprout", "id": 69, "routes": [] },
  { "name": "weepinbell", "id": 70, "routes": ["Route 19"] },
  { "name": "victreebel", "id": 71, "routes": [] },
  { "name": "carnivine", "id": 455, "routes": ["Route 14"] },
  { "name": "gastly", "id": 92, "routes": [] },
  { "name": "haunter", "id": 93, "routes": ["Route 14", "Route 19"] },
  { "name": "gengar", "id": 94, "routes": [] },
  { "name": "poliwag", "id": 60, "routes": ["Route 15", "Route 16"] },
  { "name": "poliwhirl", "id": 61, "routes": ["Route 15", "Route 16"] },
  { "name": "poliwrath", "id": 62, "routes": [] },
  { "name": "politoed", "id": 186, "routes": [] },
  { "name": "ekans", "id": 23, "routes": [] },
  { "name": "arbok", "id": 24, "routes": [] },
  { "name": "stunfisk", "id": 618, "routes": ["Route 14"] },
  { "name": "barboach", "id": 339, "routes": [] },
  { "name": "whiscash", "id": 340, "routes": [] },
  { "name": "purrloin", "id": 509, "routes": [] },
  { "name": "liepard", "id": 510, "routes": ["Route 15"] },
  { "name": "poochyena", "id": 261, "routes": [] },
  { "name": "mightyena", "id": 262, "routes": ["Route 15"] },
  { "name": "patrat", "id": 504, "routes": [] },
  { "name": "watchog", "id": 505, "routes": [] },
  { "name": "pawniard", "id": 624, "routes": ["Route 15"] },
  { "name": "bisharp", "id": 625, "routes": [] },
  { "name": "klefki", "id": 707, "routes": ["Route 15", "Route 16"] },
  { "name": "murkrow", "id": 198, "routes": [] },
  { "name": "honchkrow", "id": 430, "routes": [] },
  { "name": "foongus", "id": 590, "routes": ["Route 15", "Route 16"] },
  { "name": "amoonguss", "id": 591, "routes": ["Route 20"] },
  { "name": "lotad", "id": 270, "routes": [] },
  { "name": "lombre", "id": 271, "routes": ["Route 15", "Route 16"] },
  { "name": "ludicolo", "id": 272, "routes": [] },
  { "name": "buizel", "id": 418, "routes": [] },
  { "name": "floatzel", "id": 419, "routes": ["Route 21"] },
  { "name": "basculin", "id": 550, "routes": ["Route 15", "Route 16"] },
  { "name": "phantump", "id": 708, "routes": ["Route 16"] },
  { "name": "trevenant", "id": 709, "routes": ["Route 20"] },
  { "name": "pumpkaboo", "id": 710, "routes": ["Route 16"] },
  { "name": "gourgeist", "id": 711, "routes": [] },
  { "name": "litwick", "id": 607, "routes": ["Route 16"] },
  { "name": "lampent", "id": 608, "routes": [] },
  { "name": "chandelure", "id": 609, "routes": [] },
  { "name": "rotom", "id": 479, "routes": [] },
  { "name": "magnemite", "id": 81, "routes": [] },
  { "name": "magneton", "id": 82, "routes": [] },
  { "name": "magnezone", "id": 462, "routes": [] },
  { "name": "voltorb", "id": 100, "routes": [] },
  { "name": "electrode", "id": 101, "routes": [] },
  { "name": "trubbish", "id": 568, "routes": [] },
  { "name": "garbodor", "id": 569, "routes": [] },
  { "name": "swinub", "id": 220, "routes": [] },
  { "name": "piloswine", "id": 221, "routes": [] },
  { "name": "mamoswine", "id": 473, "routes": ["Route 17"] },
  { "name": "bergmite", "id": 712, "routes": [] },
  { "name": "avalugg", "id": 713, "routes": [] },
  { "name": "cubchoo", "id": 613, "routes": [] },
  { "name": "beartic", "id": 614, "routes": [] },
  { "name": "smoochum", "id": 238, "routes": [] },
  { "name": "jynx", "id": 124, "routes": [] },
  { "name": "vanillite", "id": 582, "routes": [] },
  { "name": "vanillish", "id": 583, "routes": [] },
  { "name": "vanilluxe", "id": 584, "routes": [] },
  { "name": "snover", "id": 459, "routes": ["Route 17"] },
  { "name": "abomasnow", "id": 460, "routes": [] },
  { "name": "delibird", "id": 225, "routes": ["Route 17"] },
  { "name": "sneasel", "id": 215, "routes": ["Route 17"] },
  { "name": "weavile", "id": 461, "routes": [] },
  { "name": "timburr", "id": 532, "routes": [] },
  { "name": "gurdurr", "id": 533, "routes": ["Route 18"] },
  { "name": "conkeldurr", "id": 534, "routes": [] },
  { "name": "torkoal", "id": 324, "routes": ["Route 18"] },
  { "name": "sandshrew", "id": 27, "routes": [] },
  { "name": "sandslash", "id": 28, "routes": [] },
  { "name": "aron", "id": 304, "routes": [] },
  { "name": "lairon", "id": 305, "routes": ["Route 18"] },
  { "name": "aggron", "id": 306, "routes": [] },
  { "name": "larvitar", "id": 246, "routes": [] },
  { "name": "pupitar", "id": 247, "routes": ["Route 18"] },
  { "name": "tyranitar", "id": 248, "routes": [] },
  { "name": "heatmor", "id": 631, "routes": ["Route 18"] },
  { "name": "durant", "id": 632, "routes": ["Route 18"] },
  { "name": "spinarak", "id": 167, "routes": [] },
  { "name": "ariados", "id": 168, "routes": ["Route 22"] },
  { "name": "spearow", "id": 21, "routes": [] },
  { "name": "fearow", "id": 22, "routes": [] },
  { "name": "cryogonal", "id": 615, "routes": [] },
  { "name": "skarmory", "id": 227, "routes": [] },
  { "name": "noibat", "id": 714, "routes": [] },
  { "name": "noivern", "id": 715, "routes": [] },
  { "name": "gligar", "id": 207, "routes": ["Route 19"] },
  { "name": "gliscor", "id": 472, "routes": [] },
  { "name": "hoothoot", "id": 163, "routes": [] },
  { "name": "noctowl", "id": 164, "routes": ["Route 20"] },
  { "name": "igglybuff", "id": 174, "routes": [] },
  { "name": "jigglypuff", "id": 39, "routes": ["Route 20"] },
  { "name": "wigglytuff", "id": 40, "routes": [] },
  { "name": "shuppet", "id": 353, "routes": [] },
  { "name": "banette", "id": 354, "routes": [] },
  { "name": "zorua", "id": 570, "routes": [] },
  { "name": "zoroark", "id": 571, "routes": ["Route 20"] },
  { "name": "gothita", "id": 574, "routes": [] },
  { "name": "gothorita", "id": 575, "routes": ["Route 20"] },
  { "name": "gothitelle", "id": 576, "routes": [] },
  { "name": "bonsly", "id": 438, "routes": [] },
  { "name": "sudowoodo", "id": 185, "routes": ["Route 20"] },
  { "name": "spinda", "id": 327, "routes": ["Route 21"] },
  { "name": "teddiursa", "id": 216, "routes": [] },
  { "name": "ursaring", "id": 217, "routes": ["Route 21"] },
  { "name": "lickitung", "id": 108, "routes": ["Route 22"] },
  { "name": "lickilicky", "id": 463, "routes": [] },
  { "name": "scyther", "id": 123, "routes": ["Route 21", "Route 22"] },
  { "name": "scizor", "id": 212, "routes": [] },
  { "name": "ditto", "id": 132, "routes": [] },
  { "name": "swablu", "id": 333, "routes": ["Route 21"] },
  { "name": "altaria", "id": 334, "routes": ["Route 21"] },
  { "name": "druddigon", "id": 621, "routes": ["Route 21"] },
  { "name": "deino", "id": 633, "routes": [] },
  { "name": "zweilous", "id": 634, "routes": [] },
  { "name": "hydreigon", "id": 635, "routes": [] },
  { "name": "dratini", "id": 147, "routes": [] },
  { "name": "dragonair", "id": 148, "routes": [] },
  { "name": "dragonite", "id": 149, "routes": [] },
  { "name": "xerneas", "id": 716, "routes": [] },
  { "name": "yveltal", "id": 717, "routes": [] },
  { "name": "zygarde", "id": 718, "routes": [] },
  { "name": "mewtwo", "id": 150, "routes": [] }
];

export const POKEMON_TYPE_COLORS: { [key: string]: { background: string; text: string; border?: string } } = {
  normal: { background: 'bg-gray-400', text: 'text-black' },
  fire: { background: 'bg-red-500', text: 'text-white' },
  water: { background: 'bg-blue-500', text: 'text-white' },
  electric: { background: 'bg-yellow-400', text: 'text-black' },
  grass: { background: 'bg-green-500', text: 'text-white' },
  ice: { background: 'bg-sky-300', text: 'text-black' },
  fighting: { background: 'bg-orange-700', text: 'text-white' },
  poison: { background: 'bg-purple-500', text: 'text-white' },
  ground: { background: 'bg-yellow-600', text: 'text-white', border: 'border-yellow-700' },
  flying: { background: 'bg-indigo-300', text: 'text-black' },
  psychic: { background: 'bg-pink-500', text: 'text-white' },
  bug: { background: 'bg-lime-500', text: 'text-black' },
  rock: { background: 'bg-yellow-700', text: 'text-white', border: 'border-yellow-800' },
  ghost: { background: 'bg-purple-700', text: 'text-white' },
  dragon: { background: 'bg-indigo-700', text: 'text-white' },
  dark: { background: 'bg-gray-700', text: 'text-white' },
  steel: { background: 'bg-slate-500', text: 'text-white' },
  fairy: { background: 'bg-pink-300', text: 'text-black' },
};

export const POKEMON_STAT_COLORS: { [key: string]: string } = {
  hp: 'bg-red-500',
  attack: 'bg-orange-500',
  defense: 'bg-yellow-500',
  'special-attack': 'bg-blue-500',
  'special-defense': 'bg-green-500',
  speed: 'bg-pink-500',
};

export const STANDARD_POKEMON_TYPES: string[] = [
  "normal", "fire", "water", "electric", "grass", "ice", "fighting", "poison",
  "ground", "flying", "psychic", "bug", "rock", "ghost", "dragon", "dark",
  "steel", "fairy"
].sort();


export const OFFICIAL_ARTWORK_URL = (id: number) => `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/${id}.png`;
export const SPRITE_URL = (id: number) => `https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/${id}.png`;

export const capitalize = (s: string): string => {
  if (!s) return '';
  return s.charAt(0).toUpperCase() + s.slice(1).toLowerCase().replace(/-/g, ' ');
};

export const formatId = (id: number): string => `#${id.toString().padStart(3, '0')}`;

export const getUniqueRoutes = (pokemonList: BasePokemon[]): string[] => {
  const allRoutes = new Set<string>();
  pokemonList.forEach(pokemon => {
    pokemon.routes?.forEach(route => {
      allRoutes.add(route);
    });
  });
  return Array.from(allRoutes).sort((a, b) => {
    // Attempt to sort numerically if routes are like "Route X"
    const numA = parseInt(a.replace(/\D/g, ''), 10);
    const numB = parseInt(b.replace(/\D/g, ''), 10);
    if (!isNaN(numA) && !isNaN(numB)) {
      return numA - numB;
    }
    return a.localeCompare(b); // Fallback to string sort
  });
};

export const KALOS_GYM_LEADERS: GymLeaderInfo[] = [
  {
    "gym_leader": "Viola",
    "city": "Santalune City",
    "specialty": "Inseto",
    "badge_name": "Insígnia do Inseto",
    "badge_image": "https://archives.bulbagarden.net/media/upload/thumb/7/75/Bug_Badge.png/50px-Bug_Badge.png"
  },
  {
    "gym_leader": "Grant",
    "city": "Cyllage City",
    "specialty": "Pedra",
    "badge_name": "Insígnia do Penhasco",
    "badge_image": "https://archives.bulbagarden.net/media/upload/thumb/a/a6/Cliff_Badge.png/50px-Cliff_Badge.png"
  },
  {
    "gym_leader": "Korrina",
    "city": "Shalour City",
    "specialty": "Lutador",
    "badge_name": "Insígnia do Estrondo",
    "badge_image": "https://archives.bulbagarden.net/media/upload/thumb/6/64/Rumble_Badge.png/50px-Rumble_Badge.png"
  },
  {
    "gym_leader": "Ramos",
    "city": "Coumarine City",
    "specialty": "Grama",
    "badge_name": "Insígnia da Planta",
    "badge_image": "https://archives.bulbagarden.net/media/upload/thumb/1/13/Plant_Badge.png/50px-Plant_Badge.png"
  },
  {
    "gym_leader": "Clemont",
    "city": "Lumiose City",
    "specialty": "Elétrico",
    "badge_name": "Insígnia da Voltagem",
    "badge_image": "https://archives.bulbagarden.net/media/upload/thumb/3/34/Voltage_Badge.png/50px-Voltage_Badge.png"
  },
  {
    "gym_leader": "Valerie",
    "city": "Laverre City",
    "specialty": "Fada",
    "badge_name": "Insígnia da Fada",
    "badge_image": "https://archives.bulbagarden.net/media/upload/thumb/9/93/Fairy_Badge.png/50px-Fairy_Badge.png"
  },
  {
    "gym_leader": "Olympia",
    "city": "Anistar City",
    "specialty": "Psíquico",
    "badge_name": "Insígnia Psíquica",
    "badge_image": "https://archives.bulbagarden.net/media/upload/thumb/3/33/Psychic_Badge.png/50px-Psychic_Badge.png"
  },
  {
    "gym_leader": "Wulfric",
    "city": "Snowbelle City",
    "specialty": "Gelo",
    "badge_name": "Insígnia do Iceberg",
    "badge_image": "https://archives.bulbagarden.net/media/upload/thumb/5/53/Iceberg_Badge.png/50px-Iceberg_Badge.png"
  }
];
